# Generated by Django 3.2.5 on 2022-03-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidByCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=10)),
                ('covid_num_bycity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CovidHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospi_city', models.CharField(max_length=10)),
                ('county', models.CharField(max_length=20)),
                ('hospi_name', models.CharField(max_length=50)),
                ('addr', models.CharField(max_length=100)),
                ('hospi_time', models.CharField(max_length=50)),
                ('sat', models.CharField(max_length=50)),
                ('hol', models.CharField(max_length=50)),
                ('tele', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DailyCovid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covid_date', models.CharField(max_length=20)),
                ('covid_num_daily', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinePercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_order_vaccine', models.CharField(max_length=5)),
                ('percentage', models.CharField(max_length=10)),
            ],
        ),
    ]
