# Generated by Django 3.2.5 on 2022-03-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_covidhospital_hospi_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidInfoBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_bar_title', models.CharField(max_length=10)),
                ('info_bar_num', models.CharField(max_length=20)),
            ],
        ),
    ]
