# Generated by Django 3.2.5 on 2022-03-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_covidinfobar'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCovid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('country_num', models.CharField(max_length=50)),
            ],
        ),
    ]
